version: '3.9'

services:
  ishmakov_am-netology-prometheus:
    image: prom/prometheus:latest
    container_name: ishmakov_am-netology-prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./6-04/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./6-04/prometheus/test_rules.yml:/etc/prometheus/test_rules.yml   # <-- добавить ЭТО
    ports:
      - "9090:9090"
    networks:
      - ishmakov_am-my-netology-hw
    restart: unless-stopped
    depends_on:
      - ishmakov_am-netology-pushgateway

  ishmakov_am-netology-pushgateway:
    image: prom/pushgateway:latest
    container_name: ishmakov_am-netology-pushgateway
    ports:
      - "9091:9091"
    networks:
      - ishmakov_am-my-netology-hw
    restart: unless-stopped

  ishmakov_am-netology-grafana:
    image: grafana/grafana:latest
    container_name: ishmakov_am-netology-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./6-04/grafana/custom.ini:/etc/grafana/grafana.ini
    ports:
      - "80:3000"
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    networks:
      - ishmakov_am-my-netology-hw
    restart: unless-stopped
    depends_on:
      - ishmakov_am-netology-prometheus

  ishmakov_am-netology-alertmanager:
    image: prom/alertmanager:latest
    container_name: ishmakov_am-netology-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./6-04/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - ishmakov_am-my-netology-hw
    restart: unless-stopped
    depends_on:
      - ishmakov_am-netology-prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  ishmakov_am-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
